### ISSUE TITLE
Last update: yii\base\ErrorException !

### ISSUE THREAD

**Issue by StellarisAgency** [humhub/humhub-modules-cfiles#25] opened 2016-10-30 06:09 UTC
yii\base\ErrorException
Declaration of humhub\modules\cfiles\Module::enableContentContainer($container) should be compatible with humhub\modules\content\components\ContentContainerModule::enableContentContainer(humhub\modules\content\components\ContentContainerActiveRecord $container)

Error 1 in Module.php line 15.
class Module extends ContentContainerModule

**Comment by buddha87** [comment] 2016-10-30 15:01
Duplicate of https://github.com/humhub/humhub-modules-cfiles/issues/21

**Closed by buddha87** 2016-10-30 15:01 UTC
Labels: bug
